pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('sample4.1') {
                    bat 'docker build --no-cache -t vite-app .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                bat '''
                docker stop vite-container || exit 0
                docker rm vite-container || exit 0
                docker run -d -p 5173:5173 --name vite-container vite-app
                '''
            }
        }
    }
}
